image: python:latest

stages:
  - deploy

deploy_project:
  stage: deploy
  script:
    - mkdir /src
    - git clone git@gitlab.com:ooskherad/scheduling_platform.git
    - cd scheduling_platform
    - docker-compose up -d